/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.ArrayList;
import java.util.List;

import org.w3c.dom.Node;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Graph graph = new Graph();
        graph.addNode("Fellow 1");
        graph.addNode("Fellow 2");
        graph.addNode("Fellow 3");
        graph.addNode("Fellow 4");

        graph.addEdge("Fellow 1", "Fellow 2");
        graph.addEdge("Fellow 1", "Fellow 3");
        graph.addEdge("Fellow 1", "Fellow 4");
        graph.addEdge("Fellow 2", "Fellow 1");
        graph.addEdge("Fellow 2", "Fellow 3");
        graph.addEdge("Fellow 3", "Fellow 1");
        graph.addEdge("Fellow 3", "Fellow 4");
        graph.addEdge("Fellow 4", "Fellow 2");
        graph.addEdge("Fellow 4", "Fellow 3");

        System.out.println(graph.print());
        System.out.println(graph.getNodes());
        System.out.println(graph.getNeighbors("Fellow 1"));
        System.out.println(graph.size());

        Graph graph1 = new Graph();

        graph1.addNode("Pandora");
        graph1.addNode("Arendelle");
        graph1.addNode("Metroville");
        graph1.addNode("Monstroplolis");
        graph1.addNode("Narnia");
        graph1.addNode("Naboo");

        graph1.addEdge("Pandora", "Arendelle");
        graph1.addEdge("Arendelle", "Metroville");
        graph1.addEdge("Arendelle", "Monstroplolis");
        graph1.addEdge("Metroville", "Narnia");
        graph1.addEdge("Metroville", "Naboo");
        graph1.addEdge("Metroville", "Monstroplolis");
        graph1.addEdge("Monstroplolis", "Naboo");
        graph1.addEdge("Narnia", "Naboo");

        System.out.println(graph1.breadthFirst_traversal("Pandora"));

        Graph graph2 = new Graph();

        graph2.addNode("Pandora");
        graph2.addNode("Arendelle");
        graph2.addNode("Metroville");
        graph2.addNode("Monstropolis");
        graph2.addNode("Narnia");
        graph2.addNode("Naboo");

        graph2.addEdgeWithWeight("Pandora", "Arendelle", 150);
        graph2.addEdgeWithWeight("Pandora", "Metroville", 82);
        graph2.addEdgeWithWeight("Arendelle", "Metroville", 99);
        graph2.addEdgeWithWeight("Arendelle", "Monstropolis", 42);
        graph2.addEdgeWithWeight("Metroville", "Narnia", 37);
        graph2.addEdgeWithWeight("Metroville", "Naboo", 26);
        graph2.addEdgeWithWeight("Metroville", "Monstropolis", 105);
        graph2.addEdgeWithWeight("Monstropolis", "Naboo", 73);
        graph2.addEdgeWithWeight("Narnia", "Naboo", 250);

        List<String> cities = new ArrayList<>();
        cities.add("Pandora");
        cities.add("Metroville");

        List<String> cities1 = new ArrayList<>();
        cities1.add("Pandora");
        cities1.add("Naboo");
        cities1.add("Metroville");

        List<String> cities2 = new ArrayList<>();
        cities2.add("Pandora");
        cities2.add("Arendelle");
        cities2.add("Metroville");

        System.out.println("First Trip ---> " + graph2.businessTrip(graph2, cities));
        System.out.println("Second Trip ---> " + graph2.businessTrip(graph2, cities1));
        System.out.println("Third Trip ---> " + graph2.businessTrip(graph2, cities2));
    }

}