/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Graph graph = new Graph();
        graph.addNode("Fellow 1");
        graph.addNode("Fellow 2");
        graph.addNode("Fellow 3");
        graph.addNode("Fellow 4");

        graph.addEdge("Fellow 1", "Fellow 2");
        graph.addEdge("Fellow 1", "Fellow 3");
        graph.addEdge("Fellow 1", "Fellow 4");
        graph.addEdge("Fellow 2", "Fellow 1");
        graph.addEdge("Fellow 2", "Fellow 3");
        graph.addEdge("Fellow 3", "Fellow 1");
        graph.addEdge("Fellow 3", "Fellow 4");
        graph.addEdge("Fellow 4", "Fellow 2");
        graph.addEdge("Fellow 4", "Fellow 3");

        System.out.println(graph.print());
        System.out.println(graph.getNodes());
        System.out.println(graph.getNeighbors("Fellow 1"));
        System.out.println(graph.size());


        Graph graph1 = new Graph();

        graph1.addNode("Pandora");
        graph1.addNode("Arendelle");
        graph1.addNode("Metroville");
        graph1.addNode("Monstroplolis");
        graph1.addNode("Narnia");
        graph1.addNode("Naboo");

        graph1.addEdge("Pandora", "Arendelle");
        graph1.addEdge("Arendelle", "Metroville");
        graph1.addEdge("Arendelle", "Monstroplolis");
        graph1.addEdge("Metroville", "Narnia");
        graph1.addEdge("Metroville", "Naboo");
        graph1.addEdge("Metroville", "Monstroplolis");
        graph1.addEdge("Monstroplolis", "Naboo");
        graph1.addEdge("Narnia", "Naboo");


        System.out.println(graph1.breadthFirst_traversal("Pandora"));

    }
}
