/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void mergeSort(){
        int arr[] = { 20, 18, 12, 8, 5, -2 };
        assertEquals("[-2, 5, 8, 12, 18, 20]", App.sortArr(arr).toString());
    }
}
