/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int arr[] = { 8, 4, 23, 42, 16, 15 };
        sortArr(arr);
        int reverse_sorted[] = { 20, 18, 12, 8, 5, -2 };
        sortArr(reverse_sorted);
        int few_uniques[] = { 5, 12, 7, 5, 5, 7 };
        sortArr(few_uniques);
        int nearly_sorted[] = { 2, 3, 5, 7, 13, 11 };
        sortArr(nearly_sorted);

    }

    public static ArrayList<Integer> sortArr(int[] arr) {
        MergingSort mergingSort = new MergingSort();

        mergingSort.mergeSort(arr);
        mergingSort.printArray(arr);
        return mergingSort.testArray(arr);
    }

}
