/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int[] arr = { 8,4,23,42,16,15 };
        int n = arr.length;
        int[] reversed = {20,18,12,8,5,-2};
        n = reversed.length;
        int[] uniques =  {5,12,7,5,5,7};
        n = uniques.length;
        int[] near_sorted = {2,3,5,7,13,11};
        n = near_sorted.length;

        quickSort(arr, 0, n - 1);
        quickSort(reversed, 0, n - 1);
        quickSort(uniques, 0, n - 1);
        quickSort(near_sorted, 0, n - 1);
    }
    public static ArrayList quickSort(int arr[], int x , int y){
        QuickSort quickSort = new QuickSort();
        quickSort.quickSort(arr, x, y);
        quickSort.print(arr, y+1);
        return quickSort.test(arr);
    }
}
