/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

//        System.out.println(new App().getGreeting());
//
//        HashTable<String, Integer> studentAllowances = new HashTable<>();
//        studentAllowances.add("Sally", 400);
//        studentAllowances.add("Doa", 600);
//        studentAllowances.add("Farah", 700);
//        studentAllowances.add("Jason", 90000);
//        studentAllowances.add("Morgan", 800);
//        studentAllowances.add("Ammar",60000);
//        studentAllowances.add("Naim", 1000);
//        studentAllowances.add("Abdelqader",50000);
//        studentAllowances.add("Qusai", 1500);
//        studentAllowances.add("Deyaa", 10000);
//
//        System.out.println("The size is => " + studentAllowances.getSize());
//        System.out.println("The Sally allowance is => " + studentAllowances.get("Sally"));
//        System.out.println("Delete Sally => " + studentAllowances.remove("Sally"));
//        System.out.println("Is it contains Ammar? => " + studentAllowances.contains("Ammar"));
//        System.out.println("Is it contains Tom? => " + studentAllowances.contains("Tom"));

        HashMap<String, String> left = new HashMap<>();
        HashMap<String, String> right = new HashMap<>();

        left.put("fond", "enamored");
        left.put("wrath", "anger");
        left.put("diligent", "employed");
        left.put("outfit", "garb");
        left.put("guide", "usher");

        right.put("fond", "averse");
        right.put("wrath", "delight");
        right.put("diligent", "idle");
        right.put("guide", "follow");
        right.put("flow", "jam");

        System.out.println(HashTable.leftJoin(left,right));
    }


}
