/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void quickSort() {
        int arr[] = { 8, 4, 23, 42, 16, 15 };
        int n = arr.length;

        assertEquals("[4, 8, 15, 16, 23, 42]", String.valueOf(App.quickSort(arr, 0, n - 1)));
    }

}
