/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;

import java.util.Objects;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void hashTable(){
        HashTable<String, Integer> test = new HashTable<>();
        test.add("HTML", 50);
        test.add("CSS",60);
        test.add("JS",70);
        test.add("React",80);
        test.add("Java",90);
        test.remove("React");

        assertNotNull(test.contains("HTML"));
        assertTrue(test.contains("CSS"));
        assertEquals(70, test.get("JS"));
        assertFalse(test.contains("React"));
        assertNull(test.get("Bootstrap"));
    }

    @Test
    public void collision(){
        System.out.println(Objects.hashCode("JS"));
        System.out.println(Objects.hashCode("Java"));

        HashTable<String, Integer> hashTable = new HashTable<>();
        hashTable.add("HTML",50);
        hashTable.add("CSS",60);
        hashTable.add("JS",70);
        hashTable.add("Java",90);

        assertTrue(hashTable.contains("JS"));
        assertTrue(hashTable.contains("Java"));

        assertEquals(70, hashTable.get("JS"));
        assertEquals(90, hashTable.get("Java"));

    }
    @Test
    public void successfullyRetrieveValue() {
        HashTable<String,Integer>hashTable = new HashTable();
        hashTable.add("JS",70);
        hashTable.add("Python",70);
        assertEquals(70, hashTable.get("JS"));
//        assertEquals(70, hashTable.get("Python"));

    }

}
