/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;

import java.util.Objects;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void hashTable(){
        HashTable<String, Integer> test = new HashTable<>();
        test.add("HTML", 50);
        test.add("CSS",60);
        test.add("JS",70);
        test.add("React",80);
        test.add("Java",90);
        test.remove("React");

        assertNotNull(test.contains("HTML"));
        assertTrue(test.contains("CSS"));
        assertEquals(70, test.get("JS"));
        assertFalse(test.contains("React"));
        assertNull(test.get("Bootstrap"));
    }

    @Test
    public void collision(){
        System.out.println(Objects.hashCode("JS"));
        System.out.println(Objects.hashCode("Java"));

        HashTable<String, Integer> hashTable = new HashTable<>();
        hashTable.add("HTML",50);
        hashTable.add("CSS",60);
        hashTable.add("JS",70);
        hashTable.add("Java",90);

        assertTrue(hashTable.contains("JS"));
        assertTrue(hashTable.contains("Java"));

        assertEquals(70, hashTable.get("JS"));
        assertEquals(90, hashTable.get("Java"));

    }
    @Test
    public void successfullyRetrieveValue() {
        HashTable<String,Integer>hashTable = new HashTable();
        hashTable.add("JS",70);
        hashTable.add("Python",70);
        assertEquals(70, hashTable.get("JS"));
//        assertEquals(70, hashTable.get("Python"));

    }
    @Test
    public void repeatedWord(){

        HashTable<String, Integer> test = new HashTable<String, Integer>();

        String paragraph1 = "Once upon a time, there was a brave princess who...";
        assertEquals("a", test.repeatedWord(paragraph1));

        String paragraph2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only";
        assertEquals("it", test.repeatedWord(paragraph2));

        String paragraph3= "It was a queer,  sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York";
        assertEquals("summer", test.repeatedWord(paragraph3));

    }
    @Test
    public void repeatedWordNoRepeat(){

        HashTable<String, Integer> test = new HashTable<String, Integer>();

        String paragraph = "Once upon a time";
        assertEquals("There is no repeated words", test.repeatedWord(paragraph));
    }

    @Test
    public void repeatedWordEmpty(){

        HashTable<String, Integer> test = new HashTable<String, Integer>();

        String paragraph = "";
        assertEquals("There is no repeated words", test.repeatedWord(paragraph));
    }

}
